var namespaceorg_1_1semanticweb_1_1owlapi =
[
    [ "api", "namespaceorg_1_1semanticweb_1_1owlapi_1_1api.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1api" ],
    [ "apibinding", "namespaceorg_1_1semanticweb_1_1owlapi_1_1apibinding.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1apibinding" ],
    [ "change", "namespaceorg_1_1semanticweb_1_1owlapi_1_1change.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1change" ],
    [ "contract", "namespaceorg_1_1semanticweb_1_1owlapi_1_1contract.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1contract" ],
    [ "datafactory", "namespaceorg_1_1semanticweb_1_1owlapi_1_1datafactory.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1datafactory" ],
    [ "debugging", "namespaceorg_1_1semanticweb_1_1owlapi_1_1debugging.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1debugging" ],
    [ "expression", "namespaceorg_1_1semanticweb_1_1owlapi_1_1expression.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1expression" ],
    [ "io", "namespaceorg_1_1semanticweb_1_1owlapi_1_1io.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1io" ],
    [ "metrics", "namespaceorg_1_1semanticweb_1_1owlapi_1_1metrics.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1metrics" ],
    [ "model", "namespaceorg_1_1semanticweb_1_1owlapi_1_1model.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1model" ],
    [ "modularity", "namespaceorg_1_1semanticweb_1_1owlapi_1_1modularity.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1modularity" ],
    [ "normalform", "namespaceorg_1_1semanticweb_1_1owlapi_1_1normalform.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1normalform" ],
    [ "profiles", "namespaceorg_1_1semanticweb_1_1owlapi_1_1profiles.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1profiles" ],
    [ "rdf", "namespaceorg_1_1semanticweb_1_1owlapi_1_1rdf.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1rdf" ],
    [ "reasoner", "namespaceorg_1_1semanticweb_1_1owlapi_1_1reasoner.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1reasoner" ],
    [ "util", "namespaceorg_1_1semanticweb_1_1owlapi_1_1util.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1util" ],
    [ "vocab", "namespaceorg_1_1semanticweb_1_1owlapi_1_1vocab.html", "namespaceorg_1_1semanticweb_1_1owlapi_1_1vocab" ],
    [ "AbstractCompositeOntologyChange", "classorg_1_1semanticweb_1_1owlapi_1_1_abstract_composite_ontology_change.html", "classorg_1_1semanticweb_1_1owlapi_1_1_abstract_composite_ontology_change" ],
    [ "AddClassExpressionClosureAxiom", "classorg_1_1semanticweb_1_1owlapi_1_1_add_class_expression_closure_axiom.html", "classorg_1_1semanticweb_1_1owlapi_1_1_add_class_expression_closure_axiom" ],
    [ "AmalgamateSubClassAxioms", "classorg_1_1semanticweb_1_1owlapi_1_1_amalgamate_sub_class_axioms.html", "classorg_1_1semanticweb_1_1owlapi_1_1_amalgamate_sub_class_axioms" ],
    [ "CoerceConstantsIntoDataPropertyRange", "classorg_1_1semanticweb_1_1owlapi_1_1_coerce_constants_into_data_property_range.html", "classorg_1_1semanticweb_1_1owlapi_1_1_coerce_constants_into_data_property_range" ],
    [ "ConvertEquivalentClassesToSuperClasses", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_equivalent_classes_to_super_classes.html", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_equivalent_classes_to_super_classes" ],
    [ "ConvertPropertyAssertionsToAnnotations", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_property_assertions_to_annotations.html", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_property_assertions_to_annotations" ],
    [ "ConvertSuperClassesToEquivalentClass", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_super_classes_to_equivalent_class.html", "classorg_1_1semanticweb_1_1owlapi_1_1_convert_super_classes_to_equivalent_class" ],
    [ "CreateValuePartition", "classorg_1_1semanticweb_1_1owlapi_1_1_create_value_partition.html", "classorg_1_1semanticweb_1_1owlapi_1_1_create_value_partition" ],
    [ "MakeClassesMutuallyDisjoint", "classorg_1_1semanticweb_1_1owlapi_1_1_make_classes_mutually_disjoint.html", "classorg_1_1semanticweb_1_1owlapi_1_1_make_classes_mutually_disjoint" ],
    [ "MakePrimitiveSubClassesMutuallyDisjoint", "classorg_1_1semanticweb_1_1owlapi_1_1_make_primitive_sub_classes_mutually_disjoint.html", "classorg_1_1semanticweb_1_1owlapi_1_1_make_primitive_sub_classes_mutually_disjoint" ],
    [ "OWLCompositeOntologyChange", "interfaceorg_1_1semanticweb_1_1owlapi_1_1_o_w_l_composite_ontology_change.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1_o_w_l_composite_ontology_change" ],
    [ "RemoveAllDisjointAxioms", "classorg_1_1semanticweb_1_1owlapi_1_1_remove_all_disjoint_axioms.html", "classorg_1_1semanticweb_1_1owlapi_1_1_remove_all_disjoint_axioms" ],
    [ "ShortForm2AnnotationGenerator", "classorg_1_1semanticweb_1_1owlapi_1_1_short_form2_annotation_generator.html", "classorg_1_1semanticweb_1_1owlapi_1_1_short_form2_annotation_generator" ],
    [ "SplitSubClassAxioms", "classorg_1_1semanticweb_1_1owlapi_1_1_split_sub_class_axioms.html", "classorg_1_1semanticweb_1_1owlapi_1_1_split_sub_class_axioms" ]
];