var namespaceorg_1_1semanticweb_1_1owlapi_1_1normalform =
[
    [ "NegationalNormalFormConverter", "classorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_negational_normal_form_converter.html", "classorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_negational_normal_form_converter" ],
    [ "NormalFormRewriter", "interfaceorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_normal_form_rewriter.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_normal_form_rewriter" ],
    [ "OWLObjectComplementOfExtractor", "classorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_o_w_l_object_complement_of_extractor.html", "classorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_o_w_l_object_complement_of_extractor" ]
];