var namespaceorg_1_1semanticweb_1_1owlapi_1_1model =
[
    [ "AddAxiom", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_axiom.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_axiom" ],
    [ "AddImport", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_import.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_import" ],
    [ "AddOntologyAnnotation", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_ontology_annotation.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_add_ontology_annotation" ],
    [ "AnnotationChange", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_annotation_change.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_annotation_change" ],
    [ "AxiomType< C extends OWLAxiom >", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_axiom_type_3_01_c_01extends_01_o_w_l_axiom_01_4.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_axiom_type_3_01_c_01extends_01_o_w_l_axiom_01_4" ],
    [ "ClassExpressionType", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_class_expression_type.html", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_class_expression_type" ],
    [ "DataRangeType", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_data_range_type.html", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_data_range_type" ],
    [ "DefaultChangeBroadcastStrategy", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_default_change_broadcast_strategy.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_default_change_broadcast_strategy" ],
    [ "DefaultImpendingChangeBroadcastStrategy", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_default_impending_change_broadcast_strategy.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_default_impending_change_broadcast_strategy" ],
    [ "EDTChangeBroadcastStrategy", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_e_d_t_change_broadcast_strategy.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_e_d_t_change_broadcast_strategy" ],
    [ "EntityType< E extends OWLEntity >", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_entity_type_3_01_e_01extends_01_o_w_l_entity_01_4.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_entity_type_3_01_e_01extends_01_o_w_l_entity_01_4" ],
    [ "ImmutableOWLOntologyChangeException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_immutable_o_w_l_ontology_change_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_immutable_o_w_l_ontology_change_exception" ],
    [ "ImpendingOWLOntologyChangeBroadcastStrategy", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_impending_o_w_l_ontology_change_broadcast_strategy.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_impending_o_w_l_ontology_change_broadcast_strategy" ],
    [ "ImpendingOWLOntologyChangeListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_impending_o_w_l_ontology_change_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_impending_o_w_l_ontology_change_listener" ],
    [ "ImportChange", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_import_change.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_import_change" ],
    [ "IRI", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_i_r_i.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_i_r_i" ],
    [ "MissingImportEvent", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_event.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_event" ],
    [ "MissingImportHandlingStrategy", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_handling_strategy.html", "enumorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_handling_strategy" ],
    [ "MissingImportListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_missing_import_listener" ],
    [ "NodeID", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_node_i_d.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_node_i_d" ],
    [ "OWLAnnotation", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation" ],
    [ "OWLAnnotationAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_assertion_axiom" ],
    [ "OWLAnnotationAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_axiom.html", null ],
    [ "OWLAnnotationAxiomVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_axiom_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_axiom_visitor" ],
    [ "OWLAnnotationAxiomVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_axiom_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_axiom_visitor_ex_3_01_o_01_4" ],
    [ "OWLAnnotationObject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_object.html", null ],
    [ "OWLAnnotationObjectVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_object_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_object_visitor" ],
    [ "OWLAnnotationObjectVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_object_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_object_visitor_ex_3_01_o_01_4" ],
    [ "OWLAnnotationProperty", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property" ],
    [ "OWLAnnotationPropertyDomainAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property_domain_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property_domain_axiom" ],
    [ "OWLAnnotationPropertyRangeAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property_range_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_property_range_axiom" ],
    [ "OWLAnnotationSubject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject" ],
    [ "OWLAnnotationSubjectVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject_visitor" ],
    [ "OWLAnnotationSubjectVisitorEx< E >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject_visitor_ex_3_01_e_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_subject_visitor_ex_3_01_e_01_4" ],
    [ "OWLAnnotationValue", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value" ],
    [ "OWLAnnotationValueVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value_visitor" ],
    [ "OWLAnnotationValueVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_annotation_value_visitor_ex_3_01_o_01_4" ],
    [ "OWLAnonymousClassExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_anonymous_class_expression.html", null ],
    [ "OWLAnonymousIndividual", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_anonymous_individual.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_anonymous_individual" ],
    [ "OWLAsymmetricObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_asymmetric_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_asymmetric_object_property_axiom" ],
    [ "OWLAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom" ],
    [ "OWLAxiomChange", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_change.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_change" ],
    [ "OWLAxiomVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_visitor" ],
    [ "OWLAxiomVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_axiom_visitor_ex_3_01_o_01_4" ],
    [ "OWLBooleanClassExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_boolean_class_expression.html", null ],
    [ "OWLCardinalityRestriction< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P >, F extends OWLPropertyRange >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_cardinality_restriction_3_01_r_01extend3753e765e18fa3094a9c5d39619b7cfe.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_cardinality_restriction_3_01_r_01extend3753e765e18fa3094a9c5d39619b7cfe" ],
    [ "OWLClass", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class" ],
    [ "OWLClassAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_assertion_axiom" ],
    [ "OWLClassAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_axiom.html", null ],
    [ "OWLClassExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression" ],
    [ "OWLClassExpressionVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression_visitor" ],
    [ "OWLClassExpressionVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_class_expression_visitor_ex_3_01_o_01_4" ],
    [ "OWLDataAllValuesFrom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_all_values_from.html", null ],
    [ "OWLDataCardinalityRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_cardinality_restriction.html", null ],
    [ "OWLDataComplementOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_complement_of.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_complement_of" ],
    [ "OWLDataExactCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_exact_cardinality.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_exact_cardinality" ],
    [ "OWLDataFactory", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_factory.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_factory" ],
    [ "OWLDataHasValue", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_has_value.html", null ],
    [ "OWLDataIntersectionOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_intersection_of.html", null ],
    [ "OWLDataMaxCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_max_cardinality.html", null ],
    [ "OWLDataMinCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_min_cardinality.html", null ],
    [ "OWLDataOneOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_one_of.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_one_of" ],
    [ "OWLDataProperty", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property.html", null ],
    [ "OWLDataPropertyAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_assertion_axiom" ],
    [ "OWLDataPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_axiom.html", null ],
    [ "OWLDataPropertyCharacteristicAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_characteristic_axiom.html", null ],
    [ "OWLDataPropertyDomainAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_domain_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_domain_axiom" ],
    [ "OWLDataPropertyExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_expression.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_expression" ],
    [ "OWLDataPropertyRangeAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_range_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_property_range_axiom" ],
    [ "OWLDataRange", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range" ],
    [ "OWLDataRangeVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range_visitor" ],
    [ "OWLDataRangeVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_range_visitor_ex_3_01_o_01_4" ],
    [ "OWLDataSomeValuesFrom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_some_values_from.html", null ],
    [ "OWLDatatype", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype" ],
    [ "OWLDatatypeDefinitionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype_definition_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype_definition_axiom" ],
    [ "OWLDatatypeRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype_restriction.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_datatype_restriction" ],
    [ "OWLDataUnionOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_union_of.html", null ],
    [ "OWLDataVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_visitor" ],
    [ "OWLDataVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_data_visitor_ex_3_01_o_01_4" ],
    [ "OWLDeclarationAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_declaration_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_declaration_axiom" ],
    [ "OWLDifferentIndividualsAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_different_individuals_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_different_individuals_axiom" ],
    [ "OWLDisjointClassesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_classes_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_classes_axiom" ],
    [ "OWLDisjointDataPropertiesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_data_properties_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_data_properties_axiom" ],
    [ "OWLDisjointObjectPropertiesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_object_properties_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_object_properties_axiom" ],
    [ "OWLDisjointUnionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_union_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_disjoint_union_axiom" ],
    [ "OWLEntity", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity" ],
    [ "OWLEntityVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity_visitor" ],
    [ "OWLEntityVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_entity_visitor_ex_3_01_o_01_4" ],
    [ "OWLEquivalentClassesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_classes_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_classes_axiom" ],
    [ "OWLEquivalentDataPropertiesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_data_properties_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_data_properties_axiom" ],
    [ "OWLEquivalentObjectPropertiesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_object_properties_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_equivalent_object_properties_axiom" ],
    [ "OWLException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_exception" ],
    [ "OWLFacetRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_facet_restriction.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_facet_restriction" ],
    [ "OWLFunctionalDataPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_functional_data_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_functional_data_property_axiom" ],
    [ "OWLFunctionalObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_functional_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_functional_object_property_axiom" ],
    [ "OWLHasKeyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_has_key_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_has_key_axiom" ],
    [ "OWLHasValueRestriction< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P >, V extends OWLObject >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_has_value_restriction_3_01_r_01extends_ddd6bdb2056f68eb0b170ea0a444249e.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_has_value_restriction_3_01_r_01extends_ddd6bdb2056f68eb0b170ea0a444249e" ],
    [ "OWLImportsDeclaration", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_imports_declaration.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_imports_declaration" ],
    [ "OWLIndividual", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual" ],
    [ "OWLIndividualAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual_axiom.html", null ],
    [ "OWLIndividualVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual_visitor" ],
    [ "OWLIndividualVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_individual_visitor_ex_3_01_o_01_4" ],
    [ "OWLInverseFunctionalObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_inverse_functional_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_inverse_functional_object_property_axiom" ],
    [ "OWLInverseObjectPropertiesAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_inverse_object_properties_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_inverse_object_properties_axiom" ],
    [ "OWLIrreflexiveObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_irreflexive_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_irreflexive_object_property_axiom" ],
    [ "OWLLiteral", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_literal.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_literal" ],
    [ "OWLLogicalAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_axiom.html", null ],
    [ "OWLLogicalAxiomVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_axiom_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_axiom_visitor" ],
    [ "OWLLogicalAxiomVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_axiom_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_axiom_visitor_ex_3_01_o_01_4" ],
    [ "OWLLogicalEntity", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_logical_entity.html", null ],
    [ "OWLMutableOntology", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_mutable_ontology.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_mutable_ontology" ],
    [ "OWLNamedIndividual", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_individual.html", null ],
    [ "OWLNamedObject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object" ],
    [ "OWLNamedObjectVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object_visitor" ],
    [ "OWLNamedObjectVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_named_object_visitor_ex_3_01_o_01_4" ],
    [ "OWLNaryAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_axiom" ],
    [ "OWLNaryBooleanClassExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_boolean_class_expression.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_boolean_class_expression" ],
    [ "OWLNaryClassAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_class_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_class_axiom" ],
    [ "OWLNaryDataRange", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_data_range.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_data_range" ],
    [ "OWLNaryIndividualAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_individual_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_individual_axiom" ],
    [ "OWLNaryPropertyAxiom< P extends OWLPropertyExpression<?,?> >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_property_axiom_3_01_p_01extends_01ea844dc139c8e4dddb91655b52ab9e06.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_nary_property_axiom_3_01_p_01extends_01ea844dc139c8e4dddb91655b52ab9e06" ],
    [ "OWLNegativeDataPropertyAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_negative_data_property_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_negative_data_property_assertion_axiom" ],
    [ "OWLNegativeObjectPropertyAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_negative_object_property_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_negative_object_property_assertion_axiom" ],
    [ "OWLObject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object" ],
    [ "OWLObjectAllValuesFrom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_all_values_from.html", null ],
    [ "OWLObjectCardinalityRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_cardinality_restriction.html", null ],
    [ "OWLObjectComplementOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_complement_of.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_complement_of" ],
    [ "OWLObjectExactCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_exact_cardinality.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_exact_cardinality" ],
    [ "OWLObjectHasSelf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_has_self.html", null ],
    [ "OWLObjectHasValue", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_has_value.html", null ],
    [ "OWLObjectIntersectionOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_intersection_of.html", null ],
    [ "OWLObjectInverseOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_inverse_of.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_inverse_of" ],
    [ "OWLObjectMaxCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_max_cardinality.html", null ],
    [ "OWLObjectMinCardinality", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_min_cardinality.html", null ],
    [ "OWLObjectOneOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_one_of.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_one_of" ],
    [ "OWLObjectProperty", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property.html", null ],
    [ "OWLObjectPropertyAssertionAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_assertion_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_assertion_axiom" ],
    [ "OWLObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_axiom.html", null ],
    [ "OWLObjectPropertyCharacteristicAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_characteristic_axiom.html", null ],
    [ "OWLObjectPropertyDomainAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_domain_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_domain_axiom" ],
    [ "OWLObjectPropertyExpression", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_expression.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_expression" ],
    [ "OWLObjectPropertyRangeAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_range_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_property_range_axiom" ],
    [ "OWLObjectSomeValuesFrom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_some_values_from.html", null ],
    [ "OWLObjectUnionOf", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_union_of.html", null ],
    [ "OWLObjectVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_visitor" ],
    [ "OWLObjectVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_object_visitor_ex_3_01_o_01_4.html", null ],
    [ "OWLOntology", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology" ],
    [ "OWLOntologyAlreadyExistsException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_already_exists_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_already_exists_exception" ],
    [ "OWLOntologyChange", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change" ],
    [ "OWLOntologyChangeBroadcastStrategy", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_broadcast_strategy.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_broadcast_strategy" ],
    [ "OWLOntologyChangeException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_exception" ],
    [ "OWLOntologyChangeListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_listener" ],
    [ "OWLOntologyChangeProgressListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_progress_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_progress_listener" ],
    [ "OWLOntologyChangesVetoedListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_changes_vetoed_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_changes_vetoed_listener" ],
    [ "OWLOntologyChangeVetoException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_veto_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_veto_exception" ],
    [ "OWLOntologyChangeVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_visitor" ],
    [ "OWLOntologyChangeVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_change_visitor_ex_3_01_o_01_4" ],
    [ "OWLOntologyCreationException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_creation_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_creation_exception" ],
    [ "OWLOntologyDocumentAlreadyExistsException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_document_already_exists_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_document_already_exists_exception" ],
    [ "OWLOntologyFactory", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_factory.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_factory" ],
    [ "OWLOntologyFactoryNotFoundException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_factory_not_found_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_factory_not_found_exception" ],
    [ "OWLOntologyFormat", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_format.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_format" ],
    [ "OWLOntologyID", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_d.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_d" ],
    [ "OWLOntologyIRIMapper", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_r_i_mapper.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_r_i_mapper" ],
    [ "OWLOntologyIRIMappingNotFoundException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_r_i_mapping_not_found_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_i_r_i_mapping_not_found_exception" ],
    [ "OWLOntologyLoaderConfiguration", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_loader_configuration.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_loader_configuration" ],
    [ "OWLOntologyLoaderListener", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_loader_listener.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_loader_listener" ],
    [ "OWLOntologyManager", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager" ],
    [ "OWLOntologyManagerFactory", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager_factory.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager_factory" ],
    [ "OWLOntologyManagerProperties", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager_properties.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_manager_properties" ],
    [ "OWLOntologyRenameException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_rename_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_rename_exception" ],
    [ "OWLOntologyResourceAccessException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_resource_access_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_resource_access_exception" ],
    [ "OWLOntologySetProvider", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_set_provider.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_set_provider" ],
    [ "OWLOntologyStorageException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storage_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storage_exception" ],
    [ "OWLOntologyStorer", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storer.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storer" ],
    [ "OWLOntologyStorerNotFoundException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storer_not_found_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_ontology_storer_not_found_exception" ],
    [ "OWLProperty< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P > >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_3_01_r_01extends_01_o_w_l_prop80b13791851fd41214e27e841bc7d0d9.html", null ],
    [ "OWLPropertyAssertionAxiom< P extends OWLPropertyExpression<?,?>, O extends OWLPropertyAssertionObject >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_assertion_axiom_3_01_p_01extenfb1174ccf37bb5b6f03e62cba90873cf.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_assertion_axiom_3_01_p_01extenfb1174ccf37bb5b6f03e62cba90873cf" ],
    [ "OWLPropertyAssertionObject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_assertion_object.html", null ],
    [ "OWLPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_axiom.html", null ],
    [ "OWLPropertyDomainAxiom< P extends OWLPropertyExpression<?,?> >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_domain_axiom_3_01_p_01extends_d1b0dc6247c6225898c4a4edc4291fb6.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_domain_axiom_3_01_p_01extends_d1b0dc6247c6225898c4a4edc4291fb6" ],
    [ "OWLPropertyExpression< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P > >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_3_01_r_01extends_0189559738b26c5864733719a0227d2300.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_3_01_r_01extends_0189559738b26c5864733719a0227d2300" ],
    [ "OWLPropertyExpressionVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_visitor" ],
    [ "OWLPropertyExpressionVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_expression_visitor_ex_3_01_o_01_4" ],
    [ "OWLPropertyRange", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_range.html", null ],
    [ "OWLPropertyRangeAxiom< P extends OWLPropertyExpression<?,?>, R extends OWLPropertyRange >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_range_axiom_3_01_p_01extends_0016041f731c436c22402051e6973b9f3.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_property_range_axiom_3_01_p_01extends_0016041f731c436c22402051e6973b9f3" ],
    [ "OWLQuantifiedDataRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_quantified_data_restriction.html", null ],
    [ "OWLQuantifiedObjectRestriction", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_quantified_object_restriction.html", null ],
    [ "OWLQuantifiedRestriction< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P >, F extends OWLPropertyRange >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_quantified_restriction_3_01_r_01extends6f80bc1237af3b841d9f88aecd41f7db.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_quantified_restriction_3_01_r_01extends6f80bc1237af3b841d9f88aecd41f7db" ],
    [ "OWLReflexiveObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_reflexive_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_reflexive_object_property_axiom" ],
    [ "OWLRestriction< R extends OWLPropertyRange, P extends OWLPropertyExpression< R, P >, F >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_restriction_3_01_r_01extends_01_o_w_l_pe9e202d85055c07a1b3bb2521accae74.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_restriction_3_01_r_01extends_01_o_w_l_pe9e202d85055c07a1b3bb2521accae74" ],
    [ "OWLRuntimeException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_runtime_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_runtime_exception" ],
    [ "OWLSameIndividualAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_same_individual_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_same_individual_axiom" ],
    [ "OWLSubAnnotationPropertyOfAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_annotation_property_of_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_annotation_property_of_axiom" ],
    [ "OWLSubClassOfAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom" ],
    [ "OWLSubClassOfAxiomSetShortCut", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom_set_short_cut.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom_set_short_cut" ],
    [ "OWLSubClassOfAxiomShortCut", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom_short_cut.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_class_of_axiom_short_cut" ],
    [ "OWLSubDataPropertyOfAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_data_property_of_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_data_property_of_axiom" ],
    [ "OWLSubObjectPropertyOfAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_object_property_of_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_object_property_of_axiom" ],
    [ "OWLSubPropertyAxiom< P extends OWLPropertyExpression<?,?> >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_property_axiom_3_01_p_01extends_01_4e9c27ceb4f20c2d0b269e98d8cfdaa5.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_property_axiom_3_01_p_01extends_01_4e9c27ceb4f20c2d0b269e98d8cfdaa5" ],
    [ "OWLSubPropertyChainOfAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_property_chain_of_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_sub_property_chain_of_axiom" ],
    [ "OWLSymmetricObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_symmetric_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_symmetric_object_property_axiom" ],
    [ "OWLTransitiveObjectPropertyAxiom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_transitive_object_property_axiom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_transitive_object_property_axiom" ],
    [ "OWLUnaryPropertyAxiom< P extends OWLPropertyExpression<?,?> >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_unary_property_axiom_3_01_p_01extends_00525a6a5c0650422f5411551b03037a5.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_o_w_l_unary_property_axiom_3_01_p_01extends_00525a6a5c0650422f5411551b03037a5" ],
    [ "PrefixManager", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_prefix_manager.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_prefix_manager" ],
    [ "RemoveAxiom", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_axiom.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_axiom" ],
    [ "RemoveImport", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_import.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_import" ],
    [ "RemoveOntologyAnnotation", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_ontology_annotation.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_remove_ontology_annotation" ],
    [ "SetOntologyID", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_set_ontology_i_d.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_set_ontology_i_d" ],
    [ "SpecificOntologyChangeBroadcastStrategy", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_specific_ontology_change_broadcast_strategy.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_specific_ontology_change_broadcast_strategy" ],
    [ "SWRLArgument", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_argument.html", null ],
    [ "SWRLAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_atom" ],
    [ "SWRLBinaryAtom< A extends SWRLArgument, B extends SWRLArgument >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_binary_atom_3_01_a_01extends_01_s_w_rc30c5b4d74ec2b23e92d0d06ccd24e5f.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_binary_atom_3_01_a_01extends_01_s_w_rc30c5b4d74ec2b23e92d0d06ccd24e5f" ],
    [ "SWRLBuiltInAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_built_in_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_built_in_atom" ],
    [ "SWRLClassAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_class_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_class_atom" ],
    [ "SWRLDArgument", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_d_argument.html", null ],
    [ "SWRLDataFactory", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_factory.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_factory" ],
    [ "SWRLDataPropertyAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_property_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_property_atom" ],
    [ "SWRLDataRangeAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_range_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_data_range_atom" ],
    [ "SWRLDifferentIndividualsAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_different_individuals_atom.html", null ],
    [ "SWRLIArgument", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_i_argument.html", null ],
    [ "SWRLIndividualArgument", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_individual_argument.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_individual_argument" ],
    [ "SWRLLiteralArgument", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_literal_argument.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_literal_argument" ],
    [ "SWRLObject", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object" ],
    [ "SWRLObjectPropertyAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_property_atom.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_property_atom" ],
    [ "SWRLObjectVisitor", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_visitor.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_visitor" ],
    [ "SWRLObjectVisitorEx< O >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_visitor_ex_3_01_o_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_object_visitor_ex_3_01_o_01_4" ],
    [ "SWRLPredicate", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_predicate.html", null ],
    [ "SWRLRule", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_rule.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_rule" ],
    [ "SWRLSameIndividualAtom", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_same_individual_atom.html", null ],
    [ "SWRLUnaryAtom< A extends SWRLArgument >", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_unary_atom_3_01_a_01extends_01_s_w_r_l_argument_01_4.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_unary_atom_3_01_a_01extends_01_s_w_r_l_argument_01_4" ],
    [ "SWRLVariable", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_variable.html", "interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_s_w_r_l_variable" ],
    [ "UnknownOWLOntologyException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_unknown_o_w_l_ontology_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_unknown_o_w_l_ontology_exception" ],
    [ "UnloadableImportException", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_unloadable_import_exception.html", "classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_unloadable_import_exception" ]
];