var namespaceorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1structural =
[
    [ "StructuralReasoner", "classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1structural_1_1_structural_reasoner.html", "classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1structural_1_1_structural_reasoner" ],
    [ "StructuralReasonerFactory", "classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1structural_1_1_structural_reasoner_factory.html", "classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1structural_1_1_structural_reasoner_factory" ]
];