var searchData=
[
  ['parsableowlontologyfactory',['ParsableOWLOntologyFactory',['../classuk_1_1ac_1_1manchester_1_1cs_1_1owl_1_1owlapi_1_1_parsable_o_w_l_ontology_factory.html',1,'uk::ac::manchester::cs::owl::owlapi']]],
  ['parseexception',['ParseException',['../classorg_1_1coode_1_1owlapi_1_1functionalparser_1_1_parse_exception.html',1,'org::coode::owlapi::functionalparser']]],
  ['parseexception',['ParseException',['../classorg_1_1coode_1_1owl_1_1krssparser_1_1_parse_exception.html',1,'org::coode::owl::krssparser']]],
  ['parseexception',['ParseException',['../classuk_1_1ac_1_1manchester_1_1cs_1_1owlapi_1_1dlsyntax_1_1parser_1_1_parse_exception.html',1,'uk::ac::manchester::cs::owlapi::dlsyntax::parser']]],
  ['parseexception',['ParseException',['../classorg_1_1coode_1_1owlapi_1_1obo_1_1parser_1_1_parse_exception.html',1,'org::coode::owlapi::obo::parser']]],
  ['parseexception',['ParseException',['../classde_1_1uulm_1_1ecs_1_1ai_1_1owlapi_1_1krssparser_1_1_parse_exception.html',1,'de::uulm::ecs::ai::owlapi::krssparser']]],
  ['parseexception',['ParseException',['../classuk_1_1ac_1_1manchester_1_1cs_1_1owl_1_1owlapi_1_1turtle_1_1parser_1_1_parse_exception.html',1,'uk::ac::manchester::cs::owl::owlapi::turtle::parser']]],
  ['parserexception',['ParserException',['../classorg_1_1semanticweb_1_1owlapi_1_1expression_1_1_parser_exception.html',1,'org::semanticweb::owlapi::expression']]],
  ['parsetypecollectionpropertyelement',['ParseTypeCollectionPropertyElement',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_parse_type_collection_property_element.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]],
  ['parsetypeliteralpropertyelement',['ParseTypeLiteralPropertyElement',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_parse_type_literal_property_element.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]],
  ['parsetyperesourcepropertyelement',['ParseTypeResourcePropertyElement',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_parse_type_resource_property_element.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]],
  ['partoftagvaluehandler',['PartOfTagValueHandler',['../classorg_1_1coode_1_1owlapi_1_1obo_1_1parser_1_1_part_of_tag_value_handler.html',1,'org::coode::owlapi::obo::parser']]],
  ['percentcharacterinentitynametestcase',['PercentCharacterInEntityNameTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_percent_character_in_entity_name_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]],
  ['pointer_3c_20k_2c_20v_20_3e',['Pointer&lt; K, V &gt;',['../interfaceuk_1_1ac_1_1manchester_1_1cs_1_1owl_1_1owlapi_1_1_internals_1_1_pointer_3_01_k_00_01_v_01_4.html',1,'uk::ac::manchester::cs::owl::owlapi::Internals']]],
  ['prefixmanager',['PrefixManager',['../interfaceorg_1_1semanticweb_1_1owlapi_1_1model_1_1_prefix_manager.html',1,'org::semanticweb::owlapi::model']]],
  ['prefixontologyformattestcase',['PrefixOntologyFormatTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1ontology_1_1_prefix_ontology_format_test_case.html',1,'org::semanticweb::owlapi::api::test::ontology']]],
  ['prefixowlontologyformat',['PrefixOWLOntologyFormat',['../classorg_1_1semanticweb_1_1owlapi_1_1vocab_1_1_prefix_o_w_l_ontology_format.html',1,'org::semanticweb::owlapi::vocab']]],
  ['primerfunctionalsyntaxroundtrippingtestcase',['PrimerFunctionalSyntaxRoundTrippingTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_primer_functional_syntax_round_tripping_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]],
  ['primerowlxmlroundtrippingtestcase',['PrimerOWLXMLRoundTrippingTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_primer_o_w_l_x_m_l_round_tripping_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]],
  ['primerrdfxmlroundtrippingtestcase',['PrimerRDFXMLRoundTrippingTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_primer_r_d_f_x_m_l_round_tripping_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]],
  ['profilevalidationtestcase',['ProfileValidationTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1ontology_1_1_profile_validation_test_case.html',1,'org::semanticweb::owlapi::api::test::ontology']]],
  ['progressmonitor',['ProgressMonitor',['../interfaceorg_1_1semanticweb_1_1owlapi_1_1util_1_1_progress_monitor.html',1,'org::semanticweb::owlapi::util']]],
  ['propertyassertionvalueshortformprovider',['PropertyAssertionValueShortFormProvider',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_property_assertion_value_short_form_provider.html',1,'org::semanticweb::owlapi::util']]],
  ['propertycharacteristicsaccessorstestcase',['PropertyCharacteristicsAccessorsTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1_property_characteristics_accessors_test_case.html',1,'org::semanticweb::owlapi::api::test']]],
  ['propertyelementlist',['PropertyElementList',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_property_element_list.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]]
];
