var searchData=
[
  ['namedclasstranslator',['NamedClassTranslator',['../classorg_1_1coode_1_1owlapi_1_1rdfxml_1_1parser_1_1_named_class_translator.html',1,'org::coode::owlapi::rdfxml::parser']]],
  ['namedconjunctchecker',['NamedConjunctChecker',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_named_conjunct_checker.html',1,'org::semanticweb::owlapi::util']]],
  ['namedindividualdeclarationwithannotationstestcase',['NamedIndividualDeclarationWithAnnotationsTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1individuals_1_1_named_individual_declaration_with_annotations_test_case.html',1,'org::semanticweb::owlapi::api::test::individuals']]],
  ['nameresolverstrategy',['NameResolverStrategy',['../enumorg_1_1coode_1_1owl_1_1krssparser_1_1_name_resolver_strategy.html',1,'org::coode::owl::krssparser']]],
  ['namespaces',['Namespaces',['../enumorg_1_1semanticweb_1_1owlapi_1_1vocab_1_1_namespaces.html',1,'org::semanticweb::owlapi::vocab']]],
  ['namespaceutil',['NamespaceUtil',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_namespace_util.html',1,'org::semanticweb::owlapi::util']]],
  ['nametagvaluehandler',['NameTagValueHandler',['../classorg_1_1coode_1_1owlapi_1_1obo_1_1parser_1_1_name_tag_value_handler.html',1,'org::coode::owlapi::obo::parser']]],
  ['negationalnormalformconverter',['NegationalNormalFormConverter',['../classorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_negational_normal_form_converter.html',1,'org::semanticweb::owlapi::normalform']]],
  ['negativedatapropertyassertionannotatedtestcase',['NegativeDataPropertyAssertionAnnotatedTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1dataproperties_1_1_negative_data_property_assertion_annotated_test_case.html',1,'org::semanticweb::owlapi::api::test::dataproperties']]],
  ['negativedatapropertyassertionaxiomtestcase',['NegativeDataPropertyAssertionAxiomTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1rdf_1_1_negative_data_property_assertion_axiom_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax::rdf']]],
  ['negativedatapropertyassertiontestcase',['NegativeDataPropertyAssertionTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1dataproperties_1_1_negative_data_property_assertion_test_case.html',1,'org::semanticweb::owlapi::api::test::dataproperties']]],
  ['negativeobjectpropertyassertionannotatedtestcase',['NegativeObjectPropertyAssertionAnnotatedTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1objectproperties_1_1_negative_object_property_assertion_annotated_test_case.html',1,'org::semanticweb::owlapi::api::test::objectproperties']]],
  ['negativeobjectpropertyassertionaxiomtestcase',['NegativeObjectPropertyAssertionAxiomTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1rdf_1_1_negative_object_property_assertion_axiom_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax::rdf']]],
  ['negativeobjectpropertyassertiontestcase',['NegativeObjectPropertyAssertionTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1objectproperties_1_1_negative_object_property_assertion_test_case.html',1,'org::semanticweb::owlapi::api::test::objectproperties']]],
  ['nestedclassexpressionroundtrippingtestcase',['NestedClassExpressionRoundTrippingTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1classexpressions_1_1_nested_class_expression_round_tripping_test_case.html',1,'org::semanticweb::owlapi::api::test::classexpressions']]],
  ['nnf',['NNF',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_n_n_f.html',1,'org::semanticweb::owlapi::util']]],
  ['nnftestcase',['NNFTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1axioms_1_1_n_n_f_test_case.html',1,'org::semanticweb::owlapi::api::test::axioms']]],
  ['node',['Node',['../interfaceorg_1_1coode_1_1owlapi_1_1functionalparser_1_1_node.html',1,'org::coode::owlapi::functionalparser']]],
  ['node_3c_20e_20extends_20owlobject_20_3e',['Node&lt; E extends OWLObject &gt;',['../interfaceorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_node_3_01_e_01extends_01_o_w_l_object_01_4.html',1,'org::semanticweb::owlapi::reasoner']]],
  ['nodeelement',['NodeElement',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_node_element.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]],
  ['nodeelementlist',['NodeElementList',['../classorg_1_1semanticweb_1_1owlapi_1_1rdf_1_1syntax_1_1_r_d_f_parser_1_1_node_element_list.html',1,'org::semanticweb::owlapi::rdf::syntax::RDFParser']]],
  ['nodefactory',['NodeFactory',['../classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1impl_1_1_node_factory.html',1,'org::semanticweb::owlapi::reasoner::impl']]],
  ['nodeid',['NodeID',['../classorg_1_1semanticweb_1_1owlapi_1_1model_1_1_node_i_d.html',1,'org::semanticweb::owlapi::model']]],
  ['noderenderer_3c_20n_20_3e',['NodeRenderer&lt; N &gt;',['../interfaceuk_1_1ac_1_1manchester_1_1cs_1_1bhig_1_1util_1_1_node_renderer_3_01_n_01_4.html',1,'uk::ac::manchester::cs::bhig::util']]],
  ['nodeset_3c_20e_20extends_20owlobject_20_3e',['NodeSet&lt; E extends OWLObject &gt;',['../interfaceorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_node_set_3_01_e_01extends_01_o_w_l_object_01_4.html',1,'org::semanticweb::owlapi::reasoner']]],
  ['nonmappingontologyirimapper',['NonMappingOntologyIRIMapper',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_non_mapping_ontology_i_r_i_mapper.html',1,'org::semanticweb::owlapi::util']]],
  ['noqnametestcase',['NoQNameTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_no_q_name_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]],
  ['normalformrewriter',['NormalFormRewriter',['../interfaceorg_1_1semanticweb_1_1owlapi_1_1normalform_1_1_normal_form_rewriter.html',1,'org::semanticweb::owlapi::normalform']]],
  ['nullchecktestcase',['NullCheckTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1_null_check_test_case.html',1,'org::semanticweb::owlapi::api::test']]],
  ['nullexplanationorderer',['NullExplanationOrderer',['../classuk_1_1ac_1_1manchester_1_1cs_1_1owl_1_1explanation_1_1ordering_1_1_null_explanation_orderer.html',1,'uk::ac::manchester::cs::owl::explanation::ordering']]],
  ['nullprogressmonitor',['NullProgressMonitor',['../classorg_1_1semanticweb_1_1owlapi_1_1util_1_1_null_progress_monitor.html',1,'org::semanticweb::owlapi::util']]],
  ['nullreasonerprogressmonitor',['NullReasonerProgressMonitor',['../classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_null_reasoner_progress_monitor.html',1,'org::semanticweb::owlapi::reasoner']]],
  ['nulltriplehandler',['NullTripleHandler',['../classuk_1_1ac_1_1manchester_1_1cs_1_1owl_1_1owlapi_1_1turtle_1_1parser_1_1_null_triple_handler.html',1,'uk::ac::manchester::cs::owl::owlapi::turtle::parser']]],
  ['numberofclasseswithmultipleinheritance',['NumberOfClassesWithMultipleInheritance',['../classorg_1_1semanticweb_1_1owlapi_1_1metrics_1_1_number_of_classes_with_multiple_inheritance.html',1,'org::semanticweb::owlapi::metrics']]],
  ['numericiristestcase',['NumericIRIsTestCase',['../classorg_1_1semanticweb_1_1owlapi_1_1api_1_1test_1_1syntax_1_1_numeric_i_r_is_test_case.html',1,'org::semanticweb::owlapi::api::test::syntax']]]
];
